### ISSUE TITLE
Parametrizing EventHandler using monad

### ISSUE THREAD

**Issue by katyo** [ocharles/engine.io#13]
I tried to create my first app using socket-io. I need run some actions in monad `m` when events occurs, but EventHandler defined as `ReaderT` with `IO` monad not `m`, i.e.

```
type EventHandler = ReaderT Socket IO
```

I would like to seen something like:

```
type EventHandler m = ReaderT Socket m
```

Is there serious reason for such decision? As I can see, parametrizing with `m` is quite possible, or not?

**Comment by ocharles** [comment]
I am no longer actively using any of these projects, so I will only be providing maintenance for now, and not new features. I think this is slightly too big a change now. If others are still requiring this functionality, please let me know and I can consider re-opening this.
