### ISSUE TITLE
Haskell clients

### ISSUE THREAD

**Issue by ericpashman** [ocharles/engine.io#18]
Oliver, do you have any interest in adding Engine.io and Socket.io client functionality to your libraries? I need to write Haskell clients and it seems sensible to start with your libraries' types and functions since the protocols are roughly symmetric in many ways.

Early stages, but at a minimum I will need your libraries to expose some additional constructors. I'll let you know what changes would be needed in more detail later, as things progress, if you're at all receptive to the idea.

I also wanted to ask you whether you know of any references approaching a spec for the protocols. Working from the Javascript reference implementations has been pretty painful so far, and much of supplementary info about the protocols that I've found around the web seems to have been obsoleted by changes to the protocols made in the last year or so.

**Comment by ocharles** [comment]
I like the sound of this. In terms of references, I'm afraid I am in the same boat as you - the reference JS implementation is really all you can go on. Most of the work in `engine-io` and `socket-io` has been from reverse engineering the actual JavaScript behavior.

**Comment by ocharles** [comment]
I wouldn't mind conditional compilation for a `socket-io` client library. In general, for GHCJS stuff I'm really hoping that Backpack is going to be the better solution though. I would say for now people should just start trying to get some code down - once we get some order we can see what we have to work with. Maybe the GHCJS interface won't really work out in a normal Haskell setting, so we may wish to split things differently.

Also, this is what I use in GHCJS to talk to `socket-io`:

```haskell
{-# LANGUAGE CPP #-}
#ifndef HLINT
{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE InterruptibleFFI #-}
#endif
module SocketIO where

import GHCJS.Types

newtype SocketIO = SocketIO (JSRef ())

#ifndef HLINT

foreign import javascript unsafe
  "io.connect($1, {'query':{}, 'forceNew': true, 'upgrade': true, 'autoConnect': false})"
  socketIONew :: JSString -> IO SocketIO

foreign import javascript unsafe
  "$1.open();"
  socketIOOpen :: SocketIO -> IO ()

foreign import javascript interruptible
  "$1.on('connect', function() { $c(); });"
  socketIOWaitForConnection :: SocketIO -> IO ()

foreign import javascript unsafe
  "$1.on($2, function(data) { $3(data); });"
  socketIOOn :: SocketIO -> JSString -> JSFun (JSRef x -> IO a) -> IO ()

foreign import javascript unsafe
  "$1.emit($2, $3);"
  socketIOEmit :: SocketIO -> JSString -> JSRef x -> IO ()

foreign import javascript unsafe
  "$1.io.disconnect()"
  socketIODisconnect :: SocketIO -> IO ()

foreign import javascript unsafe
  "$1.io.skipReconnect = false; $1.io.reconnect();"
  socketIOReconnect :: SocketIO -> IO ()

foreign import javascript unsafe
  "$1.io.opts.query[$2] = $3"
  socketIOSetQueryParameter :: SocketIO -> JSString -> JSString -> IO ()

#endif
```

**Comment by k0001** [comment]
@ocharles thanks for the quick response. OK, I'll start playing with that snippet of code you shared for the time being, and only afterwards we'll see how we can include all of this in `engine-io`/`socket-io`, as you say.

**Comment by ericpashman** [comment]
I hope to start working on this soon, but my understanding of the protocol needs to improve first—and I'm not a JS programmer, so I've been dreading further reading of the reference client's source.

FYI, I'm only interested in a pure Haskell solution. My intended use for a client is as part of a Haskell application running on a server, not in the browser. If this sounds unusual, it's because I keep running into APIs that make real-time data available only through a Socket.IO interface.

**Comment by wpoosanguansit** [comment]
Hi Eric,

I came across you comments and I am wondering if you have implemented Socket.IO client in Haskell.  I hope you do not mind sharing your effort.  Thanks for your help.

**Comment by ericpashman** [comment]
I did not end up implementing a client. My need disappeared, but if it reappears and I do end up starting work on a client, I will be sure to post here.

**Comment by ocharles** [comment]
I am no longer actively using any of this projects, so I will only be providing maintenance for now, and not new features. If anyone submits a PR providing clients, I will happily merge it, but this might be better suited to an entirely separate project.
