### ISSUE TITLE
Compilation failure (missing finally)

### ISSUE THREAD

**Issue by snoyberg** [ocharles/engine.io#22]
```
$ cabal install ./engine-io-1.2.8/ -j1
Resolving dependencies...
Configuring engine-io-1.2.8...
Building engine-io-1.2.8...
Preprocessing library engine-io-1.2.8...
[1 of 1] Compiling Network.EngineIO ( src/Network/EngineIO.hs, dist/build/Network/EngineIO.o )

src/Network/EngineIO.hs:589:7: Not in scope: ‘finally’
Failed to install engine-io-1.2.8
cabal: Error: some packages failed to install:
engine-io-1.2.8 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by ocharles** [comment]
Oh ffs. I had some local uncomitted changes - I forgot that `cabal sdist` would pick this up, despite them not being in a commit! Sorry, I'll have to fix this as `engine-io-1.2.9`.

**Comment by snoyberg** [comment]
No problem, I've got an upper bound in place right now for Stackage, so we're still using 1.2.7 there.

**Comment by ocharles** [comment]
Ok, give that a try now.

**Comment by snoyberg** [comment]
It takes a few minutes for the changes to be reflected in Hackage's 00-index.tar file. I'll close for now, and reopen if the problem still appears when I'm able to test. Thanks for the quick fix!
