### ISSUE TITLE
SocketIO.emit from an IO computation

### ISSUE THREAD

**Issue by codedmart** [ocharles/engine.io#24]
I am trying to SocketIO.emit from an IO computation. I am using the base chat example with this added:
```haskell
...
data Changes = Changes ChangeUser

instance Aeson.ToJSON Changes where
  toJSON (Changes c) = Aeson.object ["users" .= c]
...
eioServer state pool = do
...
  liftIO $ forkIO $ forever $ next cursor >>= \c -> do
      case c of
          Nothing -> undefined
          Just x -> do
              let u = resultToMaybe $ fromDatum x :: Maybe ChangeUser
              case u of
                  Nothing -> undefined
                  Just user -> SocketIO.emit "changes" (Changes user)
```
The idea is I can subscribe to changes in a rethinkdb table and I want to emit them each time I receive them.

**Comment by hansonkd** [comment]
Hi @codedmart,

I am working on something similar. I think the pattern you are looking for is to use `emitTo`

So you could do something like


```
...
data Changes = Changes ChangeUser

instance Aeson.ToJSON Changes where
  toJSON (Changes c) = Aeson.object ["users" .= c]
...
eioServer state pool = do
  curSocket <- ask --- CHANGE
...
  liftIO $ forkIO $ forever $ next cursor >>= \c -> do
      case c of
          Nothing -> undefined
          Just x -> do
              let u = resultToMaybe $ fromDatum x :: Maybe ChangeUser
              case u of
                  Nothing -> undefined
                  Just user -> SocketIO.emitTo curSocket "changes" (Changes user) --- CHANGE
```

However, if queries are likely to overlap you will probably want to use a `Map` or `IxSet` in a `TVar` to keep track of the relationship from ReQL statements and the sockets that want updates. Then on each update you can iterate over the sockets and `emitTo` them.

**Comment by codedmart** [comment]
@hansonkd Thanks! I actually figured out emitTo earlier (thanks to @bergmark). It works well for now but I will keep your suggestion in mind. Thanks again! @ocharles I am closing this, but feel free to reopen if you would like to be able to emit in an IO computation.
