### ISSUE TITLE
SocketIO.on handlers fail to trigger on adding Snap.CORS

### ISSUE THREAD

**Issue by ghost** [ocharles/engine.io#28]
Previously, this was my code for starting the snap server

``` haskell
socketIoHandler <- SocketIO.initialize EIOSnap.snapAPI
Server.quickHTTPServe $
  Core.route [ ("/socket.io", socketIoHandler)
             , ("/", Snap.serveDirectory "public")
             ]
```

The socket client was served by Snap and so there was no issue of cross-origin requests. However recently I moved the app to mobile(using Ionic). So I removed the `serveDirectory` handler essentially making the snap server into a "Socket.IO Only" server. But then the browser complained about cross origin request. I looked around and found the snap-cors package and changed the code to

``` haskell
socketIoHandler <- SocketIO.initialize EIOSnap.snapAPI
Server.quickHTTPServe $ CORS.applyCORS CORS.defaultOptions $
  Core.route [ ("/socket.io", socketIoHandler)
             , ("/", Snap.serveDirectory "public")
             ]
```

Now I don't have the cross-origin issue anymore. The client socket connects fine. However, my SocketIO.on handlers are never triggered. Upon scanning through snap error logs, I see `an exception escaped to toplevel:`.

I am using ubuntu-14.04
stack lts-3.20
ghc 7.10.2

Thank you!

**Comment by ocharles** [comment]
If you are still experiencing this problem and can provide a runnable example, I might be able to address this. Otherwise, I'm afraid I'm going to have to close this, as I'm not actively working on this project, and can only supply build fixes for now.
