### ISSUE TITLE
parseJSON get String instead of Object

### ISSUE THREAD

**Issue by bruno-cadorette** [ocharles/engine.io#29]
I'm having trouble when deserializing the data. When I trace my FromJSON instance, I get 
`String "{\"x\":1,\"y\":0}"`, instead of Object. I would expect parseJSON to get an Object, since my data is in a form of an object. It silently fail to call the callback, it would be nice to at least get an error log or something

I'm emiting `["userInput","{\"x\":0,\"y\":0}"]` from the client. 
GHC version: 7.10.3
Used packages
aeson 0.11.1.4 (same result with aeson 0.9.1)
socket-io 1.3.5
snap 0.14.0.7
linear 1.20.4 (for the V2 Float type)

Code example

```
func :: V2 Float -> ReaderT Socket IO (V2 Float)
func vec = broadcast "info" $ vec

test = on "userInput" func

instance (Aeson.ToJSON a) => Aeson.ToJSON (V2 a)  where
toJSON x =
  Aeson.object [ "x"  Aeson..= (x ^._x)
               , "y"   Aeson..= (x ^._y)
                 ]

instance FromJSON a => FromJSON (V2 a) where
parseJSON (Object obj) = trace "parseJSON ok" $ V2 <$> obj .: "x" <*> obj .: "y"
parseJSON a = traceShow a $ mzero
```

Thank you! :)

**Comment by ocharles** [comment]
The problem looks to be: 

```
["userInput","{\"x\":0,\"y\":0}"]
```

You are emitting a string, not a JSON object.

If you still have code around that reproduces this problem, let me know, but as it's over a year old, I'm going to guess you moved on. Sorry it took me quite this long to reply!
