### ISSUE TITLE
Bump upper bound for base on engine-io-snap, engine-io-wai, engine-io-yesod

### ISSUE THREAD

**Issue by erobl** [ocharles/engine.io#31]
GHC 8.0.1 uses base 4.9, which isn't allowed in the ServerAPIs, but they are in the main project.

**Comment by ocharles** [comment]
`engine-io-snap` bumped. @timjb, @codedmart  are you going to do `engine-io-yesod` and `engine-io-wai`, or would you like me to?

**Comment by codedmart** [comment]
@ocharles I can handle `engine-io-wai` today. Thanks!

**Comment by domenkozar** [comment]
This can be closed.
