### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by osa1** [ocharles/engine.io#34]
Hi all,

Since #33 merged long time ago could we have a new release on Hackage & stackage?

**Comment by codedmart** [comment]
@osa1 oops I thought I had done that. On my todo list today.

**Comment by osa1** [comment]
Ping @codedmart .

Alternatively you could give me push access ;-) My Hackage id is `OmerAgacan`.

**Comment by codedmart** [comment]
@osa1 New package is on Hackage now. Not sure if a new LTS release for Stackage is in the works with GHC 8.0, but need to do some more dep bumping all around for this to make it back in Stackage with the nightly and the next LTS.

**Comment by osa1** [comment]
Thank you!
