### ISSUE TITLE
Upper bound on `either` dependency needs to be lifted 

### ISSUE THREAD

**Issue by k0001** [ocharles/engine.io#35]
We have `either` version `5` out.

**Comment by ocharles** [comment]
Are you using this library? Do you want a maintainer bit?

**Comment by k0001** [comment]
@ocharles I was trying to get back to working on a project that I haven't touched for many months, and I am reporting issues as I find them. Sure, I can help maintain these small details if you want. Thanks.

**Comment by ocharles** [comment]
It looks more than just lifting the bound, as `either-5` no longer has `EitherT`, which this probably uses. Added you as a contributor and maintainer on Hackage.

**Comment by ocharles** [comment]
I've just release 1.2.18 which changes from `either` to `errors`.
