### ISSUE TITLE
Bump upper bound for base for engine-io-wai

### ISSUE THREAD

**Issue by ChShersh** [ocharles/engine.io#37]
GHC 8.2.2 requires `base` to be `4.10` while `engine-io-wai` has `base (>=4.6 && <4.10)`

**Comment by ocharles** [comment]
@codedmart, could you bump this and cut a new release?

**Comment by ChShersh** [comment]
I would really love to see this fixed... Because it blocks my PR:

* https://github.com/input-output-hk/cardano-sl/pull/2327

Maybe new release is not necessary. If everything just works, you can just create new revision.

**Comment by codedmart** [comment]
@ChShersh Sorry been pretty swamped. Updated in ee78d9b. On Hackage now.

**Comment by ChShersh** [comment]
@codedmart Thanks a lot!
