### ISSUE TITLE
Increasing the bound of base library. 

### ISSUE THREAD

**Issue by barankou** [ocharles/engine.io#38]
Hello, I am trying to build my project with stack using `resolver: lts-12.4` and it uses base 4.11.1.0. It would be perfect if you could increase the upper bound of base and http-types libraries, that would be great. Thank you for your efforts.

**Comment by ocharles** [comment]
Can do! I'm on holiday until next Friday, I'll bump then.

**Comment by barankou** [comment]
Thank you for your efforts and have a nice holiday.

**Comment by ocharles** [comment]
I've released new versions of all the libraries I maintain - let me know if I missed anything!
