### ISSUE TITLE
Consider adding engine.io and socket.io to stackage

### ISSUE THREAD

**Issue by qwbarch** [ocharles/engine.io#45]
Hi Ollie, would you consider adding these packages to stackage to make it more convenient for stack users?
Thanks in advance, and thank you for adding a socket.io implementation for haskell!

**Comment by ocharles** [comment]
Hi @qwbarch! Unfortunately this project is not currently maintained, so without a maintainer I don't think I can commit to keeping it up to date, like Stackage requires. If this is something you'd like to help with, let me know - I'm more than happy to hand this project over to anyone interested! 9I no longer use it, myself)

**Comment by qwbarch** [comment]
I'm not experienced enough to help out with this library yet, but perhaps one day I'll see what I can do.

Closing the issue since you've given an answer, thanks again!
