### ISSUE TITLE
Socket.io rooms and namespaces

### ISSUE THREAD

**Issue by Timoha** [ocharles/engine.io#9]
Hello, thanks a lot for this great library!

I've already implemented realtime part of my application with [websocket](https://hackage.haskell.org/package/websockets) package, however once I saw you releasing this library, I've decided to try and rewrite it using socket.io to take all of the benefits of it. However, I'm new to haskell and might need some help with transition.

As you know socket.io supports a feature [Rooms and Namespaces](http://socket.io/docs/rooms-and-namespaces/) which allows to easier manage groups of sockets (broadcast to all other sockets in group, etc). My application requires for me to have such separation, but I also need to keep track of each socket connection anyway because I need to store some data per connection. So, I was wondering whether it's worth to stick to my current structure which is a `Map` (for each room - roomId as key) of `Map`s (clientId as key, and socket + some info as value), or to consider using socket.io rooms instead and each room to have a `Map` with key of `socketId` and value of info that I need.

Please let me know what you would advise, and in case it's implementing rooms, I'll try to assist you wherever I can. Thank you!

**Comment by ocharles** [comment]
Hi. I am not actively working on this library anymore, only providing maintenance. If anyone provides a PR adding rooms/namespaces I will happily merge it.
